#!/bin/bash

set -eo pipefail

FILEPATH=$(realpath "${0}")
DIR=$(dirname "${FILEPATH}")
MROVER_BUILD_ROOT="${HOME}/.mrover"
JARVIS_ROOT=${DIR}/jarvis_files
JARVIS_VENV=${MROVER_BUILD_ROOT}/jarvis_env
PRODUCT_ENV=${MROVER_BUILD_ROOT}/build_env

run_jarvis() {
    # Runs a Jarvis command using PyInvoke
    # shellcheck source=/dev/null
    source "${JARVIS_VENV}/bin/activate"
    jarvis "--root=${DIR}" "$@"
    return $?
}

make_jarvis_env() {
    # Make virtualenv for Jarvis
    python3 -m venv "${JARVIS_VENV}"
    # shellcheck source=/dev/null
    source "${JARVIS_VENV}/bin/activate"
	pip install --upgrade pip >/dev/null
    pip install -r "${JARVIS_ROOT}/requirements.txt" >/dev/null
    pip install "${JARVIS_ROOT}/jarvis_cmd" >/dev/null
}

log() {
    echo "[ "
    echo -n $(date)
    echo " ] $1" >> $HOME/jarvis_log
}

# print and log
print() {
    log $1
    echo $1
}

if [ ! -d "${MROVER_BUILD_ROOT}" ]; then
    print "Bootstrapping..."
    # Make MRover Build Root
    mkdir -p "${MROVER_BUILD_ROOT}"
    make_jarvis_env
    print "Done!"
fi

if [ "$#" -lt 1 ]; then
    run_jarvis --help
    exit 0
fi

if [ "$1" = "implode" ]; then
    # Delete mrover build space
    log "Attempting to implode"
    rm -rf "${MROVER_BUILD_ROOT}"
    print "Imploded"
    exit 0
fi

if [ "$1" = "upgrade" ]; then
    log "upgrading"
    # Delete Jarvis env and rebuild it
    # shellcheck source=/dev/null
    source "${JARVIS_VENV}/bin/activate"
    log "Jarvis env activated"
    pip install -r "${JARVIS_ROOT}/requirements.txt" >/dev/null
    log "Requirements installed"
    pip install --upgrade "${JARVIS_ROOT}/jarvis_cmd" >/dev/null
    log "jarvis_cmd upgraded"
    exit 0
fi

if [ "$1" = "exec" ]; then
    if [ -d "${PRODUCT_ENV}" ]; then
        # shellcheck source=/dev/null
        source "${PRODUCT_ENV}/bin/activate"
        log "Prod env activated"
        shift
        exec env LD_LIBRARY_PATH="${PRODUCT_ENV}/lib:${PRODUCT_ENV}/lib/x86_64-linux-gnu" "$@"
    else
        print "You must build something in order to be able to exec a command."
    fi
    exit 0
fi

run_jarvis "$@"

